### ISSUE TITLE
Error thrown without message

### ISSUE THREAD

**Issue by niftylettuce** [ifedoroff/compound-file-js#7]
```sh
Error:
    at new FixedSizeChunkedDataview (/Users/niftylettuce/Projects/compound-file-js/src/dataview/FixedSizeChunkedDataview.ts:20:63)
    at Function.CompoundFile.fromUint8Array (/Users/niftylettuce/Projects/compound-file-js/src/CompoundFile.ts:37:33)
    at SpamScanner.parseCompoundFile (/Users/niftylettuce/Projects/spamscanner/index.js:389:30)
    at /Users/niftylettuce/Projects/spamscanner/index.js:1266:39
    at async Promise.all (index 0)
    at SpamScanner.getExecutableResults (/Users/niftylettuce/Projects/spamscanner/index.js:1255:5)
    at async Promise.all (index 2)
    at SpamScanner.scan (/Users/niftylettuce/Projects/spamscanner/index.js:1324:9)
    at /Users/niftylettuce/Projects/spamscanner/test/test.js:53:16
```

This error stems from `src/dataview/FixedSizeChunkedDataview.ts` which has this code:

```js
    constructor(chunkSize: number, dataChunks?: number[]|CFDataview[]) {
    this.chunkSize = chunkSize;
        if(dataChunks != null) {
        if(typeof dataChunks[0] === 'number') {
                if(dataChunks.length % chunkSize !== 0) throw new Error();
                const dataLength = dataChunks.length;
                const rawView = new SimpleDataview(dataChunks as number[]);
                for (let i = 0; i < dataLength; i += 512) {
                    this.chunks.push(new ReferencingSubview(rawView, i, i + 512));
                }
            } else {
                this.chunks.push(...(dataChunks as CFDataview[]));
            }
        }
    }
```

As you can see the line `if(dataChunks.length % chunkSize !== 0) throw new Error();` will cause an undefined error to be thrown.

**Comment by ifedoroff** [comment]
A descriptive error message added
